admin:
  username: admin
  password: litmus
  mode: admin

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: litmus.local
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  size: 8Gi
  storageClass: standard

serviceAccount:
  create: true
  name: litmus-admin
  annotations: {}

rbac:
  create: true
  pspEnabled: false

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi 