apiVersion: v1
kind: Service
metadata:
  name: litmuschaos-frontend-service
  namespace: litmus
spec:
  type: NodePort
  ports:
  - port: 9091
    targetPort: 8185
    nodePort: 30091
  selector:
    app.kubernetes.io/component: litmus-frontend
    app.kubernetes.io/instance: litmuschaos 