apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/mongodb
    type: DirectoryOrCreate
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: litmus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-mongodb
  namespace: litmus
spec:
  selector:
    matchLabels:
      app: chaos-mongodb
  template:
    metadata:
      labels:
        app: chaos-mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        command:
        - mongod
        - --bind_ip_all
        - --replSet
        - rs0
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: litmus
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: chaos-mongodb
  namespace: litmus
spec:
  selector:
    app: chaos-mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP 