replicaCount: 2

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

securityContext:
  runAsUser: 101
  runAsGroup: 101
  fsGroup: 101

nodeSelector: {}

tolerations: []

affinity: {}

env:
  MAX_DELAY_SECONDS: "0"
  ERROR_RATE: "0"
  DEBUG: "false"
