name: Chaos Engineering Deployment
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Kubernetes
        uses: azure/setup-kubectl@v3

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "akintunero" --password-stdin

      - name: Build & Push Hello World App
        run: |
          docker build -t hello-world-app:latest hello-world-app/
          docker tag hello-world-app:latest akintunero/hello-world-app:latest
          docker push akintunero/hello-world-app:latest

      - name: Deploy Hello World App
        run: kubectl apply -f helm/templates/hello-world-deployment.yaml
